export type Product = {
	id : string
	title : string
	price : number
	originalPrice : number
	sales : number
	image : string
	categoryId : string
	tags : string[]
}

export type Category = {
	id : string
	name : string
	icon : string
}

export type CartItem = {
	productId : string
	title : string
	price : number
	image : string
	quantity : number
	checked : boolean
}

export type TabItem = {
	key : string
	text : string
	icon : string
	activeIcon : string
	path : string
}
